version: '3.5'

services:
  postgres:
    container_name: amadeus-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: amadeus
      POSTGRES_PASSWORD: amadeus
      PGDATA: /data/postgres
    volumes:
      - postgres-amadeus:/data/postgres
    ports:
      - "5432:5432"

  kafka:
    container_name: amadeus-kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    container_name: amadeus-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

volumes:
  postgres-amadeus:
